### ISSUE TITLE
Nouvelle6

### ISSUE THREAD

**Issue by xlilix2312** [Mmellet/La_Fabrique_de_Poe#13]

**Comment by Mmellet** [comment]
vous avez rencontré un problème particulier ?

**Comment by xlilix2312** [comment]
Non, je suis desolée. Je ne voulais pas créer un "Issue", c'était par méprise et après je ne savais pas comment le supprimer.

Mais merci beaucoup quand même et bonne soirée à vous!
________________________________
Von: Margot Mellet ***@***.***>
Gesendet: Mittwoch, 22. Februar 2023 01:28
An: Mmellet/La_Fabrique_de_Poe ***@***.***>
Cc: xlilix2312 ***@***.***>; Author ***@***.***>
Betreff: Re: [Mmellet/La_Fabrique_de_Poe] Nouvelle6 (Issue #13)


vous avez rencontré un problème particulier ?
