### ISSUE TITLE
Pull/Push

### ISSUE THREAD

**Issue by cgermain97** [Mmellet/La_Fabrique_de_Poe#20]
Salut Margot,

Quand j'essaie de créer un pull request pour déposer mon travail ça ne fonctionne pas... 
J'ai pull dans vs codium, commit et push, puis fait une requête dans git hub.

**Comment by andreannegrenier** [comment]
Moi aussi ça ne fonctionne pas.

**Comment by Mmellet** [comment]
Bonjour Camille, Bonjour Andréanne, 

En quoi cela ne fonctionne-t-il pas ? 

J'ai de mon côté valider une pull request de chacune : les pulls request requièrent toujours ma relecture et mon approbation mais c'est normal. 

Est-ce que vous pouvez m'expliciter ce qu'il se passe de votre côté ?

**Comment by cgermain97** [comment]
Je ne savais pas qu'il fallait ton approbation... tout semble fonctionner, mais ma nouvelle ne semble pas s'afficher...

**Comment by Mmellet** [comment]
Oui je l'ai remarqué : le problème se situe dans les métadonnées : il semble y avoir un espace au tout début des métadonnées qui fait qu'elles s'affichent toutes sur une ligne alors qu'elles devraient être disposées sur plusieurs lignes.

**Comment by andreannegrenier** [comment]
J'avais commencer à éditer avant que ça soit accepté, mais ce que j'ai fait semble avoir disparut. Je ne suis aussi incapable de faire des espaces en markdown, des tirets longs (--)et des notes de bas de page ([^1]) dans l'espace d'édition

**Comment by cgermain97** [comment]
Oh... Qu'est-ce que je dois faire pour arranger la situation?

**Comment by Mmellet** [comment]
@andreannegrenier vous avez travaillé en local ou sur la plateforme en ligne ? 

Je ne suis pas sûre de comprendre le problème des tirets longs : si vous allez voir dans l'édition de la note.md (https://github.com/Mmellet/La_Fabrique_de_Poe/tree/master/content/posts) les tirets longs s'affichent.

Pour les espaces insécables, c'est le même raccourcis dans VScodium, seulement ils ne s'affichent pas.

**Comment by andreannegrenier** [comment]
en ligne

**Comment by andreannegrenier** [comment]
Dans le fond avec stylo, il fallait rejouter des tirets longs et des espaces insécables. Mais, ça ne semble pas marcher avec Github.

**Comment by Mmellet** [comment]
@andreannegrenier pour l'édition en ligne vous devez avoir accès au mode édit de votre nouvelle (en vous plaçant bien sur votre branche) 

![Screenshot 2023-02-25 at 16-19-50 La_Fabrique_de_Poe_nouvelle2 md at master · Mmellet_La_Fabrique_de_Poe](https://user-images.githubusercontent.com/40469215/221380189-9235748b-5f50-4115-b01d-ed6b5556ad9e.png)

Ce n'est pas le cas ?

**Comment by Mmellet** [comment]
pour @cgermain97 dans vos métadonnées il faut remplacer 

weight = Numero 3 

par 

```
weight = 3
```

Pour l'instant cela a bloqué le déploiement mais pas de panique cela arrive

**Comment by andreannegrenier** [comment]
oui j'ai accès au mode edit et je crois que j'ai en essayant de faire un pull request tantot, j'ai créer par accident plusieurs branches

**Comment by Mmellet** [comment]
pour distinguer les deux issues qui ne sont pas sur les mêmes problématiques, @cgermain97 on peut faire le suivi sur cette issue : https://github.com/Mmellet/La_Fabrique_de_Poe/issues/23

**Comment by Mmellet** [comment]
ah oui en effet vous en avez créé 3...

attendez je regarde mais pour être bien sûre : vous avez travaillé sur chacun des 3 ?

**Comment by andreannegrenier** [comment]
Je ne suis pas sûre, mais je vais conserver [andreannegrenier-patch-3]

**Comment by andreannegrenier** [comment]
Pis dans le fond si je comprends bien les tirets se font tout seul et il n'y a pas d'espace insécable à mettre?

**Comment by Mmellet** [comment]
je vais réunir vos branches et je crois avoir compris comment vous en êtes arrivée à créer 3 branches en plus de la vôtre.  

lorsque vous enregistrez en ligne votre travail ou que vous commitez dans github : vous avez le choix de commiter sur votre branche ou de créer une autre branche : 

![Screenshot 2023-02-25 at 16-35-01 Editing La_Fabrique_de_Poe_nouvelle11 md at master · Mmellet_La_Fabrique_de_Poe](https://user-images.githubusercontent.com/40469215/221380691-aa5cf017-082d-4217-8e58-a28c34e912fd.png)

Choisissez de rester sur votre branche qui doit être : andreanne)

**Comment by Mmellet** [comment]
Je vais la réunion de vos branches et je vous dis quand c'est bon

**Comment by andreannegrenier** [comment]
okay merci

**Comment by Mmellet** [comment]
Ok c'est bon ! 

Pour la suite, sélectionnez bien votre branche andréanne, et vous pouvez faire le travail d'édition en sélectionnant le mode édit (l'icone du crayon) : il faut en effet ajouter les tirets longs avec --, pour les espaces insécables, vous n'êtes pas obligée.

**Comment by andreannegrenier** [comment]
les tiret (--) en mode edit ne donne pas des tiret long en preview

**Comment by Mmellet** [comment]
Ok alors formulé ainsi ça y est je comprends ce que vous voulez dire : la preview de github n'est pas ce sur quoi vous devez vous fier : c'est la preview en ligne qui est importante https://mmellet.github.io/La_Fabrique_de_Poe/

**Comment by andreannegrenier** [comment]
Donc si je comprends bien, il y a juste les tirets longs, les italique, le gras, les titres et les notes de bas de pages à éditer

**Comment by andreannegrenier** [comment]
Est-ce que cela prend un certain temps avant d'apparaitre sur le preview en ligne ? J'ai fait des changements sur ma branche andréanne qui n'apparaissent pas sur ce preview.

**Comment by Mmellet** [comment]
oui alors pour le moment, comme je le disais à camille le déploiement est interrompu

Pour le travail à faire : oui + ce qui est indiqué dans les slides du cours

**Comment by andreannegrenier** [comment]
Okay merci beaucoup
