### ISSUE TITLE
Weight dans métadonnées

### ISSUE THREAD

**Issue by Mmellet** [Mmellet/La_Fabrique_de_Poe#23]
Dans les métadonnées, le weight doit être renseigné ainsi : 

```
weight = 2 

```

**Comment by Mmellet** [comment]
@cgermain97 j'ai modifié la ligne problématique pour permettre de reprendre le déploiement du site afin que les autres puissent voir leurs modifications en ligne

**Comment by Mmellet** [comment]
si vous êtes en local : n'oubliez-pas de faire un git pull ;)

**Comment by cgermain97** [comment]
Merci beaucoup!!
