### ISSUE TITLE
trouver nouvelle 5

### ISSUE THREAD

**Issue by marieperr** [Mmellet/La_Fabrique_de_Poe#33]
Bonjour,
lorsque je vais dans content/posts, je ne trouve pas ma nouvelle (5). Est-ce possible que je l'aie mise à la mauvaise place? @Mmellet

**Comment by Mmellet** [comment]
Le problème venait du fait que votre branche n'était pas à jour avec la branche master : c'est résolu, vous devriez voir votre nouvelle désormais !
