### ISSUE TITLE
Affichage des nouvelles sur le site web

### ISSUE THREAD

**Issue by Alexya2002** [Mmellet/La_Fabrique_de_Poe#42]
Bonjour, je me demandais pourquoi est-ce qu'il y a seulement les nouvelles 1, 2, 3, 5, 7, 8 et 11 qui sont affichés sur le site web ? Est-ce qu'il faut faire une autre procédure que les pull requests ?

**Comment by Mmellet** [comment]
Je vous ai commenté votre pull request : il y a un espace au début des métadonnées : 

```
 +++
```
