### ISSUE TITLE
Nouvelle 12

### ISSUE THREAD

**Issue by Alexya2002** [Mmellet/La_Fabrique_de_Poe#44]
Bonjour, je ne comprends vraiment pas pourquoi il y a trois fois le texte sur le site web. Est-ce qu'il y a eu un problème ?

**Comment by Mmellet** [comment]
de ce que je vois, votre commit comprend l'ajout x2 de la nouvelle : https://github.com/Mmellet/La_Fabrique_de_Poe/commit/bd507cbafb50442161dfbb0747b12ecb8efc9c9b

question est ce que vous avez commitez sur votre branche en ligne ou en local ? quelle commande avez-vous utilisé pour commiter ? Parce qu'il apparaît que vous avez maintenant 3 branches en plus à votre nom

**Comment by Alexya2002** [comment]
Je pense que je comprends pourquoi il y a plusieurs fois la nouvelle. J'étais en local, mais je n'étais pas capable de pull. Donc, j'ai essayé plutôt de modifier en ligne en copiant ce que ce j'avais fait en local. Par contre, je n'ai aucune idée comment régler le problème .

**Comment by Alexya2002** [comment]
En fait, on m'indiquait en local sur le terminal que ça avait bien pull, mais je ne voyais pas apparaître nul part. Donc, j'ai décidé de procéder autrement. 
<img width="403" alt="Capture d’écran 2023-03-01 144000" src="https://user-images.githubusercontent.com/122815385/222246894-aba414db-de58-43d1-8838-5bba4cf74bfa.png">

**Comment by Alexya2002** [comment]
Est-ce que ça prend un certain temps avant de s'afficher ?

**Comment by Mmellet** [comment]
qu'est ce qui ne s'affichait pas ?

**Comment by Alexya2002** [comment]
La nouvelle version de la nouvelle

**Comment by Mmellet** [comment]
alors si vous avez édité la nouvelle version de votre nouvelle sur github en ligne dans une des branche nommée -patch : oui elle ne sera pas récupérée sur votre branche alexya en local. 

Donc nouvelle question : lorsque vous avez fait vos modifications en ligne : lorsque vous avez commité est ce que vous vous souvenez avoirs choisi de commiter en créant une nouvelle branche ? Normalement c'est ce qui expliquerait la création des 3 branches "patch"

![Screenshot 2023-02-25 at 16-35-01 Editing La_Fabrique_de_Poe_nouvelle11 md at master · Mmellet_La_Fabrique_de_Poe](https://user-images.githubusercontent.com/40469215/222248889-84113b5a-411e-4f1d-b2ee-9393d70eeaf1.png)

**Comment by Alexya2002** [comment]
Ah oui c'est ça ! Je ne pensais pas qu'on pouvait choisir entre la première ou la deuxième option. C'était sur le deuxième choix, donc créer une nouvelle branche.

**Comment by Mmellet** [comment]
Ok mystère résolu alors, pour l'avenir il faudra commiter sur votre branche (alexya), pour que vous puissez voir vos modifications sur votre branche alexya, je l'ai mise à jour avec les branches patch (que j'ai supprimé car elles ne servent plus), vous pouvez désormais faire un git pull sur votre terminal

**Comment by Alexya2002** [comment]
Super, merci pour votre aide ! C'est vraiment apprécié ! Par contre, je viens d'essayer de le faire et un message d'erreur s'est affiché 
<img width="460" alt="Capture d’écran 2023-03-01 150228" src="https://user-images.githubusercontent.com/122815385/222253066-92d59cda-d428-45bb-9549-42fdd19ff9e1.png">

**Comment by Mmellet** [comment]
ah oui c'est un conflit parce que vous avez dû changer des choses avant de puller, que vous dit votre 

```
git status
```

?

**Comment by Alexya2002** [comment]
Oui, j'ai modifié le chapter
<img width="479" alt="Capture d’écran 2023-03-01 151148" src="https://user-images.githubusercontent.com/122815385/222254944-27212ce5-8e7c-4054-a48e-19ea2927d905.png">

**Comment by Mmellet** [comment]
ok alors selon les mofications, soit : 

- vous ne souhaitez pas les conservez et vous faîtes : 

```
git restore content/posts/nouvelle12.md
git pull
```

- vous les conservez parce qu'elles sont plus actuelles que la version en ligne et donc : 

```
git add content/posts/nouvelle12.md
git commit -m "votre commentaire"
git push
```
 si vous souhaitez revenir à une branche propre, avec un mode un peu plus radical qui ne tiendra pas compte de vos dernière modifcations en ligne : 

```
git stash

```

**Comment by Alexya2002** [comment]
Heu... je ne suis pas tout à fait sûre de savoir quelle option est la meilleure dans mon cas ? Il faudrait que je fasse :
git add content/posts/nouvelle12.md
git commit -m "votre commentaire"
git push
si je veux garder les modifications que j'ai faites en ligne ?

**Comment by Mmellet** [comment]
Non c'est si vous voulez gardez les modifications faîtes en local :)

**Comment by Alexya2002** [comment]
Ah oui, oups je me suis trompée.

**Comment by Alexya2002** [comment]
Ça n'a pas fonctionné
<img width="499" alt="Capture d’écran 2023-03-01 152845" src="https://user-images.githubusercontent.com/122815385/222258105-f41ae0c2-24e0-43d4-8313-7e3a2617bcbe.png">

**Comment by Mmellet** [comment]
alors faîtes git pull pour voir ce qu'il vous dit

**Comment by Alexya2002** [comment]
Et voilà ! Je suis vraiment désolé que ça soit aussi compliqué
<img width="508" alt="Capture d’écran 2023-03-01 153457" src="https://user-images.githubusercontent.com/122815385/222259271-112560b3-0957-4c51-befa-542a66f42141.png">

**Comment by Mmellet** [comment]
mais non pas de stress, c'est normal que cela arrive, c'est juste plus long à régler à distance ;) 

faites : 

```
git add static/images/portraitovale.jpg
git commit -m "ajout image pour merge"
git pull
```

**Comment by Alexya2002** [comment]
<img width="652" alt="Capture d’écran 2023-03-01 153912" src="https://user-images.githubusercontent.com/122815385/222259888-bdac47ee-2fdd-41ec-b2a5-b5138aebb9be.png">

**Comment by Mmellet** [comment]
est-ce que vous vous souvenez des modifications que vous avez fait en local ? est ce que c'était des modifications longues ? sinon le plus simple, serait de restaurer l'ancienne version de la nouvelle avec un 

```
git restore content/posts/nouvelle12.md

```

et après normalement le git pull devrait passer

**Comment by Alexya2002** [comment]
Ça n'a pas fonctionné malheureusement
<img width="652" alt="Capture d’écran 2023-03-01 153912" src="https://user-images.githubusercontent.com/122815385/222262218-a64646d0-a90a-437a-83a4-0d598b2d0238.png">

**Comment by Alexya2002** [comment]
Oups, mauvaise capture
<img width="460" alt="Capture d’écran 2023-03-01 155115" src="https://user-images.githubusercontent.com/122815385/222262282-6ec3716e-de51-47bf-b796-c168e9c52127.png">

**Comment by Mmellet** [comment]
alors 

```
git merge content/posts/nouvelle12.md"

```

**Comment by Alexya2002** [comment]
<img width="444" alt="15" src="https://user-images.githubusercontent.com/122815385/222262768-6eebc837-5940-47b3-9ffe-e3d57267d4cb.png">

**Comment by Mmellet** [comment]
hummm ...
et git status vous dit quoi désormais ?

**Comment by Alexya2002** [comment]
<img width="418" alt="16" src="https://user-images.githubusercontent.com/122815385/222263203-42c126fc-1eef-422f-a329-4fb13605353b.png">

**Comment by Mmellet** [comment]
alors on va essayer : 

```
git stash
```

**Comment by Alexya2002** [comment]
<img width="278" alt="17" src="https://user-images.githubusercontent.com/122815385/222264162-3ec90403-9a63-4982-b535-215b39f3765f.png">

**Comment by Alexya2002** [comment]
<img width="667" alt="Capture d’écran 2023-03-01 160303" src="https://user-images.githubusercontent.com/122815385/222264413-7710f84c-975f-4f97-9cf7-156a7012781a.png">

**Comment by Mmellet** [comment]
ah oui alors ça va être plus simple ! vous allez pouvoir modifier directement la nouvelle pour résoudre le conflit !

**Comment by Alexya2002** [comment]
Je pense que ça a fonctionné, je viens de faire un git push. Est-ce que tout semble correct ? 
<img width="410" alt="Capture d’écran 2023-03-01 160616" src="https://user-images.githubusercontent.com/122815385/222265114-faadc167-2944-4198-95c6-ab6a7b687b3d.png">

**Comment by Mmellet** [comment]
ok oui et maintenant git pull  et puis git status : qu'est ce qu'ils vous disent ?

**Comment by Alexya2002** [comment]
<img width="353" alt="Capture d’écran 2023-03-01 160941" src="https://user-images.githubusercontent.com/122815385/222265616-60dd6d9c-27af-45df-81d4-ef9042201255.png">

**Comment by Alexya2002** [comment]
Merci à vous ! Mais, je pense que j'ai compris, pourquoi mon premier essai a échoué. J'ai juste fait git push, je n'ai pas ajouté git pull.
